### PR TITLE
Add a --skip-tag command line argument

### PR DESCRIPTION
**Pull request by BehindTheMath**
This option skips checking for, adding, and pushing a tag with the new version number.

### CODE REVIEW

**Comment by MoOx** [comment]
Not sure what is the use case for this. In what scenario would you want to skip tagging the version?

**Comment by BehindTheMath** [comment]
It's been a while, so I don't remember exactly. It came up when I was working on a release for Pjax. I think I wanted to be able to add the tag manually afterwards.

**Comment by MoOx** [comment]
This will defeat the purpose of this package: ensure that you publish an already tagged version.
Going to close this one. Feel free to bring more arguments to the table :)

**Comment by BehindTheMath** [comment]
I'll be back when it's time to publish the next version of Pjax :grinning:

**Pull request closed without merging**
